# Generated by Django 5.1.4 on 2024-12-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
