# Generated by Django 5.1.4 on 2024-12-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministracionProductos', '0002_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
